[CI] Add pre-commit hooks
pasqal-io/pasqal-cloud pull request #92
Opened 2023-06-29 13:57 UTC by Mildophin

2023-06-30 09:14 UTC, Mildophin commented
got a doubt about the utility of

with:
    fetch-depth: 0
    
if you got any clue Raphael

2023-06-30 09:14 UTC, Altiire requested changes

2023-06-30 09:14 UTC, Altiire commented on .pre-commit-config.yaml
> +      - id: shellcheck
I don't see any shell script so I think it's better to remove it

2023-06-30 09:14 UTC, Altiire commented on .pre-commit-config.yaml
> +      - id: hadolint-docker
No docker in this repo so this needs to be removed

2023-06-30 09:21 UTC, Altiire approved these changes

2023-06-30 09:23 UTC, Mildophin commented
> got a doubt about the utility of
> 
> with: fetch-depth: 0
> 
> if you got any clue Raphael

@Altiire

2023-06-30 09:42 UTC, Altiire commented
> got a doubt about the utility of
> 
> with: fetch-depth: 0
> 
> if you got any clue Raphael

fetch depth 0 = you fetch the whole history. for a first time it can be nice but for the others, you can set it to 50 so you only have the 50 last commits

2023-06-30 09:44 UTC, Mildophin commented
> > got a doubt about the utility of
> > with: fetch-depth: 0
> > if you got any clue Raphael
> 
> fetch depth 0 = you fetch the whole history. for a first time it can be nice but for the others, you can set it to 50 so you only have the 50 last commits

so it checks if not secrets were leaked in the 50 last commits ? In the case we merge it to dev it will check all the 50 commits before ?

2023-06-30 09:47 UTC, Altiire commented
> > > got a doubt about the utility of
> > > with: fetch-depth: 0
> > > if you got any clue Raphael
> > 
> > 
> > fetch depth 0 = you fetch the whole history. for a first time it can be nice but for the others, you can set it to 50 so you only have the 50 last commits
> 
> so it checks if not secrets were leaked in the 50 last commits ? In the case we merge it to dev it will check all the 50 commits before ?

if it has run for this PR then the whole history got already checked. if we set the depth to 50, the last 50 commits will be checked every time

2023-07-03 10:29 UTC, oliver-gordon commented on .github/workflows/check-secrets-leak.yml
> +name: Verify if no secrets were leaked
`Verify no secrets are leaked`
or
`Verify if secrets were leaked`

2023-07-03 10:29 UTC, oliver-gordon commented on README.md
> +To make sure you have a good code quality, please install pre-commit, it will trigger useful linting checks:
nit: reword: `We use pre-commit hooks to enforce some code linting, you can install pre-commit with Python pip.`

2023-07-03 12:58 UTC, Mildophin commented
I added the pydantic dependency to this MR @oliver-gordon as our current code is not supported by pydantic 2.0

2023-07-03 13:23 UTC, penguinoneshaw approved these changes

2023-07-03 13:25 UTC, merged